<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AskingKitten.Contracts\AskingKitten.Contracts.csproj" />
      <ProjectReference Include="..\AskingKitten.Entities\AskingKitten.Entities.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Comments\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    </ItemGroup>

</Project>
