<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AskingKitten.Contracts\AskingKitten.Contracts.csproj" />
      <ProjectReference Include="..\AskingKitten.Entities\AskingKitten.Entities.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.9" />
      <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.0" />
    </ItemGroup>

</Project>
