<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AskingKitten.Application\AskingKitten.Application.csproj" />
      <ProjectReference Include="..\AskingKitten.Contracts\AskingKitten.Contracts.csproj" />
      <ProjectReference Include="..\AskingKitten.Entities\AskingKitten.Entities.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Analyzer" Version="1.0.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.9" />
      <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0-2.final">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Comments\" />
    </ItemGroup>

</Project>
